"""Initial schema

Revision ID: 1c1c0d34d62f
Revises: 
Create Date: 2026-03-12 21:32:38.906491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1c0d34d62f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corridor_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('bounds', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridor_versions_version_tag'), 'corridor_versions', ['version_tag'], unique=True)
    op.create_table('mode_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.String(), nullable=True),
    sa.Column('delta', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_proposal_id'), 'proposals', ['proposal_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_proposal_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('mode_states')
    op.drop_index(op.f('ix_corridor_versions_version_tag'), table_name='corridor_versions')
    op.drop_table('corridor_versions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
