"""Initial schema

Revision ID: a355e023c649
Revises: 
Create Date: 2026-03-12 21:32:39.570490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a355e023c649'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('quality_deviation', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reasons', sa.JSON(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('weights_at_time', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_store_key'), 'experience_store', ['key'], unique=False)
    op.create_table('policy_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_registry_policy_id'), 'policy_registry', ['policy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_registry_policy_id'), table_name='policy_registry')
    op.drop_table('policy_registry')
    op.drop_index(op.f('ix_experience_store_key'), table_name='experience_store')
    op.drop_table('experience_store')
    # ### end Alembic commands ###
