"""Initial schema

Revision ID: 4bd94f79b02f
Revises: 
Create Date: 2026-03-12 21:32:39.876231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd94f79b02f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('armed', sa.Boolean(), nullable=True),
    sa.Column('last_write', sa.JSON(), nullable=True),
    sa.Column('last_good_setpoint', sa.JSON(), nullable=True),
    sa.Column('last_readback', sa.JSON(), nullable=True),
    sa.Column('connector_state', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ot_state')
    op.drop_table('ot_config')
    # ### end Alembic commands ###
