"""Initial schema

Revision ID: 4b0406a21a10
Revises: 
Create Date: 2026-03-12 21:32:39.214875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0406a21a10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('quality_deviation', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reasons', sa.JSON(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_entries_batch_id'), 'kpi_entries', ['batch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_entries_batch_id'), table_name='kpi_entries')
    op.drop_table('kpi_entries')
    # ### end Alembic commands ###
